'use client';
import{useEffect,useState}from'react';import Shell from'../../components/Shell';import{apiGet,apiPost,apiUpload}from'../../lib/api';
export default function Compras(){const[s,setS]=useState<any[]>([]),[c,setC]=useState<any[]>([]),[results,setResults]=useState<any[]>([]),[q,setQ]=useState(''),[selected,setSelected]=useState<any>(null),[searching,setSearching]=useState(false),[f,setF]=useState<any>({supplier_id:'',product_id:'',quantity:1,unit_cost:0}),[supplier,setSupplier]=useState(''),[file,setFile]=useState<File|null>(null),[msg,setMsg]=useState('');
const load=async()=>{const[suppliers,purchases]=await Promise.all([apiGet('/suppliers'),apiGet('/purchases?limit=5')]);setS(suppliers);setC(purchases)};
useEffect(()=>{load()},[]);
useEffect(()=>{const t=setTimeout(async()=>{const term=q.trim();if(term.length<2){setResults([]);return}setSearching(true);try{setResults(await apiGet(`/products/search?q=${encodeURIComponent(term)}&limit=20`))}finally{setSearching(false)}},300);return()=>clearTimeout(t)},[q]);
function pickProduct(x:any){setSelected(x);setQ(`${x.sku} - ${x.name}`);setResults([]);setF({...f,product_id:x.id,unit_cost:x.cost||f.unit_cost||0})}
async function submit(e:any){e.preventDefault();if(!f.supplier_id||!f.product_id){alert('Seleccioná proveedor y producto');return}await apiPost('/purchases',{...f,supplier_id:+f.supplier_id,product_id:+f.product_id,quantity:+f.quantity,unit_cost:+f.unit_cost});setF({supplier_id:'',product_id:'',quantity:1,unit_cost:0});setSelected(null);setQ('');setMsg('Compra manual registrada correctamente.');load()}
async function upload(){if(!supplier||!file)return;const r=await apiUpload(`/purchases/import/${supplier}`,file);setMsg(`Compra importada: ${r.imported} productos, sin producto ${r.missing_products}, total $${Math.round(r.total)}`);load()}
return <Shell><h1>Compras</h1>{msg&&<div className='card'>{msg}</div>}<br/><div className='grid' style={{gridTemplateColumns:'1fr 1fr'}}><div className='card'><h3>Importar compra por proveedor</h3><p className='small'>Template compra: SKU, CANTIDAD, COSTO. Al importar suma stock, actualiza costo y registra historial.</p><select className='input' value={supplier} onChange={e=>setSupplier(e.target.value)}><option value=''>Proveedor</option>{s.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><br/><br/><input type='file' onChange={e=>setFile(e.target.files?.[0]||null)}/><br/><br/><button className='btn' onClick={upload}>Subir compra</button></div><div className='card'><h3>Compra manual</h3><form onSubmit={submit}><div className='form-row'><select className='input' value={f.supplier_id} onChange={e=>setF({...f,supplier_id:e.target.value})}><option value=''>Proveedor</option>{s.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><div style={{position:'relative'}}><input className='input' placeholder='Buscar SKU o producto' value={q} onChange={e=>{setQ(e.target.value);setSelected(null);setF({...f,product_id:''})}}/><p className='small' style={{margin:'6px 0 0'}}>Escribí al menos 2 letras o números.</p>{searching&&<div className='small'>Buscando...</div>}{results.length>0&&<div className='card' style={{position:'absolute',zIndex:20,left:0,right:0,top:48,maxHeight:260,overflow:'auto',padding:8}}>{results.map(x=><button type='button' key={x.id} className='input' style={{display:'block',width:'100%',textAlign:'left',marginBottom:6}} onClick={()=>pickProduct(x)}><b>{x.sku}</b> - {x.name}<br/><span className='small'>Stock {x.stock} · ${x.sale_price}</span></button>)}</div>}</div><input className='input' type='number' placeholder='Cantidad' value={f.quantity} onChange={e=>setF({...f,quantity:e.target.value})}/><input className='input' type='number' placeholder='Costo' value={f.unit_cost} onChange={e=>setF({...f,unit_cost:e.target.value})}/></div>{selected&&<p className='small'>Producto seleccionado: <b>{selected.sku}</b> - {selected.name}</p>}<button className='btn'>Registrar compra</button></form></div></div><br/><h3>Últimas compras / importaciones</h3><p className='small'>Se muestran solo los últimos 5 movimientos para que cargue rápido.</p><div className='table-wrap'><table className='table'><thead><tr><th>ID</th><th>Proveedor</th><th>Producto</th><th>Cant</th><th>Costo</th><th>Total</th></tr></thead><tbody>{c.length===0&&<tr><td colSpan={6} className='muted'>Sin compras recientes</td></tr>}{c.map(x=><tr key={x.id}><td>{x.id}</td><td>{x.supplier_name||x.supplier_id}</td><td><b>{x.sku}</b> {x.product_name||x.product_id}</td><td>{x.quantity}</td><td>${x.unit_cost}</td><td>${x.total}</td></tr>)}</tbody></table></div></Shell>}
